server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Файл с информацией о текущем логе для работы после перезапуска
positions:
  filename: /tmp/positions.yaml

# Куда засылать логи
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: library-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: library
          __path__: /app/logs/library.log
# Создание меток для поиска по логам
    pipeline_stages:
      # Объявление потенциально интересующих нас меток в логах формата JSON
      - json:
          expressions:
            level: level
            trace_id: trace_id
            book_id: book_id
            author_id: author_id
            layer: layer
            table: table
      # Группировка по меткам
      - labels:
          level:
          trace_id:
          book_id:
          author_id:
          layer:
          table: